import builtins from "builtin-modules";
import { spawn } from 'child_process';
import chokidar from "chokidar";
import esbuild from "esbuild";
import { copyFile, mkdir, readFile } from 'fs/promises';
import { dirname, join } from 'path';
import process from "process";
import { fileInliner } from "./build/file-inliner.mjs";
import { galleryDocs } from "./build/gallery-docs.mjs";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// directory of the external repo to copy files into
const WIKI_REPO = "../obsidian-note-toolbar-wiki";

// files to copy into the external repo after build
// each entry: { src: <source path>, dest: <path relative to WIKI_REPO> }
const WIKI_FILES = [
	{ src: "docs/api/INoteToolbarApi.Interface.default.md", dest: "Note-Toolbar-API.md" },
	{ src: "docs/gallery.md", dest: "Gallery.md" },
];

const typecheckPlugin = {
	name: 'typecheck',
	setup(build) {
		build.onEnd(async () => {
			return new Promise((resolve) => {
				console.log('[typecheck] running...');
				const tsc = spawn('tsc', ['-noEmit', '-skipLibCheck'], {
					stdio: 'inherit' // pipes stdout/stderr directly, preserving colors
				});
				tsc.on('close', (code) => {
					if (code === 0) {
						console.log('\x1b[32m[typecheck] ✓ passed\x1b[0m');
					} else {
						console.log('\x1b[31m[typecheck] ✗ failed\x1b[0m');
					}
					resolve();
				});
			});
		});
	},
};

const typedocPlugin = {
	name: 'api-docs',
	setup(build) {
		build.onEnd(() => {
			const typedoc = spawn('typedoc', [
				'src/Api/INoteToolbarApi.ts',
				'src/Api/IToolbar.ts',
				'src/Api/IItem.ts',
				'--readme',
				'none'
			]);
			typedoc.stderr.on('data', (data) => {
				console.error(`${data}`);
			});
		});
  	},
};

const eslintPlugin = {
	name: 'eslint',
	setup(build) {
		build.onEnd(async () => {
			return new Promise((resolve) => {
				console.log('[eslint] running...');
				const eslint = spawn('npx', ['eslint', '.', '--ext', '.ts'], {
					stdio: 'inherit',
					shell: true // needed for Windows
				});
				eslint.on('close', (code) => {
					if (code === 0) {
						console.log('\x1b[32m[eslint] ✓ passed\x1b[0m');
					} else {
						console.log('\x1b[33m[eslint] ⚠ warnings/errors found\x1b[0m');
					}
					resolve();
				});
			});
		});
	},
};

// copy configured files into the external wiki repo, only if contents changed
const copyToWikiPlugin = {
	name: 'copy-to-wiki',
	setup(build) {
		build.onEnd(async () => {
			for (const { src, dest } of WIKI_FILES) {
				const destPath = join(WIKI_REPO, dest);
				try {
					const [srcContent, destContent] = await Promise.all([
						readFile(src),
						readFile(destPath).catch(() => null), // null if dest doesn't exist yet
					]);
					if (destContent && srcContent.equals(destContent)) {
						console.log(`[copy-to-wiki] no change: ${src}`);
						continue;
					}
					await mkdir(dirname(destPath), { recursive: true });
					await copyFile(src, destPath);
					console.log(`\x1b[32m[copy-to-wiki] ✓ ${src} → ${destPath}\x1b[0m`);
				} catch (error) {
					console.error(`\x1b[31m[copy-to-wiki] ✗ failed to copy ${src}: ${error.message}\x1b[0m`);
				}
			}
		});
	},
};

// inline files into CSS, and validates it
const stylesPlugin = {
	name: 'styles',
	setup(build) {
	  build.onEnd(async () => {
		try {
			await fileInliner('src/Styles/styles.css', 'styles.css');
		} catch (error) {
			console.error("\x1b[31m[styles] Error:\x1b[0m", error);
			process.exit(1);
		}
		// use esbuild to report CSS syntax errors
		await esbuild.build({
			entryPoints: ['styles.css'],
			bundle: false,
			write: false,
		}).catch(() => process.exit(1));
	  });
	},
  };

const galleryDocsPlugin = {
	name: 'gallery-docs',
	setup(build) {
	  build.onEnd(async () => {
		try {
			await galleryDocs('src/Gallery/gallery-items.json', 'src/Gallery/gallery.json', 'docs/gallery-items.md');
		} 
		catch (error) {
			console.error("\x1b[31m[gallery-docs] Error:\x1b[0m", error);
			process.exit(1);
		}
		try {
			await fileInliner('docs/gallery-header.md', 'docs/gallery.md');
		} catch (error) {
			console.error("\x1b[31m[file-inliner-plugin] Error:\x1b[0m", error);
			process.exit(1);
		}
	  });
	},
  };

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	loader: {
		'.md': 'text',
	},
	logLevel: "info",
	plugins: [stylesPlugin, typedocPlugin, galleryDocsPlugin, typecheckPlugin, eslintPlugin, copyToWikiPlugin],
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	minify: prod ? true : false,
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();

	// watch for changes to files outside the build process
	const watcher = chokidar.watch(['src/Api', 'src/Styles']);
	watcher.on('ready', () => {
		console.log('[watch] watching for changes...');
	});
	watcher.on('change', async (path) => {
		console.log(`[watch] file changed: ${path}`);
		try {
			await context.rebuild();
		} 
		catch (error) {
			console.error('[watch] rebuild failed:', error);
		}
	});
}