import esbuild from "esbuild";
import chokidar from "chokidar";
import { fileInliner } from "./build/file-inliner.mjs";
import { galleryDocs } from "./build/gallery-docs.mjs";
import process from "process";
import { spawn } from 'child_process';
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");

// use esbuild to check CSS for errors
// DISABLED for now until I have time to fix the noted issues
// await esbuild.build({
// 	entryPoints: ['src/styles.css'],
// 	bundle: false,
// 	write: false
// }).catch(() => process.exit(1));

const typecheckPlugin = {
	name: 'typecheck',
	setup(build) {
		build.onEnd(async () => {
			return new Promise((resolve) => {
				console.log('[typecheck] running...');
				const tsc = spawn('tsc', ['-noEmit', '-skipLibCheck'], {
					stdio: 'inherit' // pipes stdout/stderr directly, preserving colors
				});
				
				tsc.on('close', (code) => {
					if (code === 0) {
						console.log('\x1b[32m[typecheck] ✓ passed\x1b[0m');
					} else {
						console.log('\x1b[31m[typecheck] ✗ failed\x1b[0m');
					}
					resolve();
				});
			});
		});
	},
};

// inline files into CSS
const fileInlinerPlugin = {
	name: 'file-inliner-plugin',
	setup(build) {
	  build.onEnd(async () => {
		try {
			await fileInliner('src/Styles/styles.css', 'styles.css');
		} catch {
			process.exit(1);
		}
	  });
	},
  };

const galleryDocsPlugin = {
	name: 'gallery-docs',
	setup(build) {
	  build.onEnd(async () => {
		try {
			await galleryDocs('src/Gallery/gallery-items.json', 'src/Gallery/gallery.json', 'docs/wiki/gallery.md');
		} 
		catch (error) {
			console.log("[esbuild] Error generating Gallery docs:", error);
			process.exit(1);
		}
	  });
	},
  };

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins],
	format: "cjs",
	target: "es2018",
	loader: {
		'.md': 'text',
	},
	logLevel: "info",
	plugins: [fileInlinerPlugin, galleryDocsPlugin, typecheckPlugin],
	sourcemap: prod ? false : "inline",
	treeShaking: true,
	minify: prod ? true : false,
	outfile: "main.js",
});

if (prod) {
	await context.rebuild();
	process.exit(0);
} else {
	await context.watch();

	// watch for changes to files outside the build process
	const watcher = chokidar.watch(['src/Styles/*']);
	watcher.on('change', async (path) => {
		console.log(`[watch] file changed: ${path}`);
		try {
			await context.rebuild();
		} 
		catch {
			console.error('[watch] rebuild failed:', error);
		}
	});

	console.log('[watch] watching for changes...');
}